image: marcopeg/gitpod-workspace-hasura:v2.0.0-beta.1-alpha.1

tasks:
  # Hasura Engine
  # =============
  - name: Hasura
    command: HELLO=world
      HASURA_GRAPHQL_SERVER_PORT=8080
      HASURA_GRAPHQL_ADMIN_SECRET="hasura"
      HASURA_GRAPHQL_JWT_SECRET="{\"type\":\"HS256\",\"key\":\"h2leOvdgjwpV0As5L8rZlV3VDVOsOmwk\"}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anonymous"
      hasura_start
    openIn: right

#ports:
#  - port: 8080
#    onOpen: open-preview
#    visibility: private

    
